# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = app/store/database/migrations

# template for migration file names
file_template = %%(rev)s_%%(slug)s

# timezone for timestamps
timezone =

# database connection string
# sqlalchemy.url = driver://user:pass@localhost/dbname
# Мы будем загружать его из .env в env.py
sqlalchemy.url =

# ... etc.
